#================================================================
# Misskey Web Configuration
#================================================================

### サーバーの管理者情報
# ex) "Your Name <youremail@example.com>"
maintainer: "travis-ci"

### アクセスするときのドメイン
host: "misskey.xyz"

### アクセスするときのポート
# サーバー内部でlistenするポートではありません。ブラウザでアクセスするときの最終的なポートです。
# 内部でプロキシを使用していたりなどの理由で、リクエストを待ち受けるポートを指定する場合は bindPorts の項目を設定してください。
ports:
  http: 80
  https: 443
  streaming: 3000

### ユーザーのクライアントに関する設定をストアするDB(Mongo)の情報
mongo:
  uri: "mongodb://localhost/misskey-web"
  options:
   user: ""
   pass: ""

# 2016年5月現在、APIがストリーミングを提供していないため直接APIサーバーのRedisに繋ぐ必要があるので、その情報
redis:
  host: "localhost"
  pass: ""

### TLS設定
https:
  enable: false

### APIサーバー設定
api:
  host: "api.misskey.xyz"
  port: 8080
  secure: false
  pass: "apikey"

# よく分からない
cookiePass: "a"

# セッションIDを保存するCookieのキー
sessionKey: "hmsk"

# よく分からない
sessionSecret: "supersecret"

### reCAPTCHA設定
# SEE: https://www.google.com/recaptcha/intro/index.html
recaptcha:
  # サイトキー
  siteKey: ""
  # シークレット
  secretKey: ""

### Search Console設定
# SEE: https://support.google.com/webmasters/answer/35179?hl=ja
googleSiteVerification: ""

bindIp: null

### Web待ち受けポート
bindPorts:
  http: 80
  https: 443
  streaming: 3000

### テーマカラー
themeColor: "#ec6b43"